### PR TITLE
Resolve 'NameError: uninitialized constant Glimmer::DataBinding' on Windows

### PR DESCRIPTION
**Pull request by rubycoder**
The glimmer command works fine in 4.20.6.0, but in 4.20.7.0 through 4.20.10.0, on Windows 7 SP1 and Windows 10, the glimmer command gets an error:

```
c:\> glimmer
NameError: uninitialized constant Glimmer::DataBinding
      const_missing at org/jruby/RubyModule.java:3766
      const_missing at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/nested_inherited_jruby_include_package-0.3.0/lib/core/src/main/ruby/jruby/java/core_ext/module.rb:72
  <class:Animation> at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.20.10.0/lib/glimmer/swt/custom/animation.rb:32
    <module:Custom> at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.20.10.0/lib/glimmer/swt/custom/animation.rb:30
       <module:SWT> at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.20.10.0/lib/glimmer/swt/custom/animation.rb:28
   <module:Glimmer> at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.20.10.0/lib/glimmer/swt/custom/animation.rb:27
             <main> at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.20.10.0/lib/glimmer/swt/custom/animation.rb:26
            require at org/jruby/RubyKernel.java:974
            require at C:/jruby-9.2.19.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
             <main> at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.20.10.0/lib/glimmer/dsl/swt/animation_expression.rb:24
            require at org/jruby/RubyKernel.java:974
            require at C:/jruby-9.2.19.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
             <main> at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.20.10.0/lib/glimmer/dsl/swt/dsl.rb:25
               each at org/jruby/RubyArray.java:1820
             <main> at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.20.10.0/lib/glimmer/dsl/swt/dsl.rb:25
            require at org/jruby/RubyKernel.java:974
            require at C:/jruby-9.2.19.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
             <main> at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.20.10.0/lib/glimmer-dsl-swt.rb:45
            require at org/jruby/RubyKernel.java:974
   require_relative at org/jruby/RubyKernel.java:1002
             <main> at C:/jruby-9.2.19.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.20.10.0/bin/glimmer:26
               load at org/jruby/RubyKernel.java:1009
             <main> at c:\jruby-9.2.19.0\bin\glimmer:23
```			 
This error does not occur on Mac Catalina 10.15.7 or Ubuntu 20.04.2 LTS.

The glimmer command is an easy way to reproduce this, but simply requiring 'glimmer-dsl-swt' will result in the same error message.

Removing line 32:
```
        include Glimmer::DataBinding::ObservableModel
```
from 
/home/rubycoder/.rvm/gems/jruby-9.2.19.0/gems/glimmer-dsl-swt-4.20.10.0/lib/glimmer/swt/custom/animation.rb
resolves this issue, and glimmer then runs on Windows 7 SP1, Windows 10, Catalina 10.15.7 and Ubuntu 20.04.2 LTS

### CODE REVIEW

**Comment by AMaleh** [comment]
I'll take a look.

That line must not be removed because it adds data-binding support to animation, but perhaps a require statement for it can be added to animation. I'll know once I get a chance to look at the code in a few hours.

Thanks for reporting

**Comment by AMaleh** [comment]
Should be resolved in v4.20.10.2

Please confirm and let me know.

**Comment by rubycoder** [comment]
Thanks for your lightning fast response!  I really appreciate it.

I'm racing to get to an appointment, but with v4.20.10.2 on Windows 7 SP1, ran "C:\> glimmer" and also did require 'glimmer-dsl-swt' in jirb.  Both worked fine.

I'll do some more testing, including running the specs, either tonight or tomorrow for sure, and let you know the results.  But so far it looks perfect.

Thanks again!

**Comment by rubycoder** [comment]
With v4.20.11.0 on Windows 7 SP1, ran "C:\> glimmer" and also did require 'glimmer-dsl-swt' in jirb.  Both succeeded.

Ran 'rake spec' and all specs passed, with 3 pending which I think is the expected result.

I also tried all the above on Windows 10 and Ubuntu 20.04.2 LTS, with exactly the same successful results.

Thanks!

**Comment by AMaleh** [comment]
Good enough! Closing...

**Pull request closed without merging**
